// mcp-vue-code/components/AddConsumerAuth.vue
<template>
  <el-drawer
    title="添加消费者授权"
    @close="handleClose"
    destroy-on-close
    size="700px"
  >
    <el-form
      ref="formRef"
      :model="formData"
      label-width="100px"
      label-position="left"
      :rules="rules"
    >
      <el-form-item label="授权范围">MCP服务</el-form-item>
      <el-form-item label="消费者" prop="consumerId">
        <el-select
          v-model="formData.consumerId"
          placeholder="请选择消费者"
          filterable
          style="width: 100%"
        >
          <el-option
            v-for="item in consumerList"
            :key="item.value"
            :label="item.label"
            :value="item.value"
          />
        </el-select>
      </el-form-item>
    </el-form>
    <div class="drawer__footer">
      <el-button @click="$emit('update:modelValue', false)">取消</el-button>
      <el-button type="primary" @click="handleAddConsumerAuth">添加</el-button>
    </div>
  </el-drawer>
</template>

<script>
  import { getAppListByPage } from '@/api/application'
  import { addConsumers } from '@/api/mcp'
  export default {
    name: 'AddConsumerAuth',
    props: {
      mcpName: {
        type: String,
        default: '',
      },
      strategyConfigId: {
        type: String,
        default: '',
      },
    },
    emits: ['update:modelValue', 'added'],
    data() {
      return {
        formData: {
          consumerId: '',
        },
        consumerList: [],
        rules: {
          consumerId: [
            { required: true, message: '请选择消费者', trigger: 'blur' },
          ],
        },
      }
    },
    mounted() {
      this.fetchConsumerList()
    },
    methods: {
      async fetchConsumerList() {
        try {
          const res = await getAppListByPage({ pageNo: 1, pageSize: 100 })
          if (res && res.data && Array.isArray(res.data.records)) {
            this.consumerList = res.data.records.map((item) => ({
              label: item.appName,
              value: item.appId,
            }))
          }
        } catch (e) {
          this.$message.error('获取消费者列表失败')
        }
      },
      handleAddConsumerAuth() {
        this.$refs.formRef.validate((valid) => {
          if (valid) {
            addConsumers({
              mcpServerName: this.$route.params.mcpId,
              consumers: [this.formData.consumerId],
            }).then((res) => {
              if (res.code === 200) {
                this.$message.success('授权成功')
                this.$emit('update:modelValue', false)
                this.$emit('added')
              }
            })
          }
        })
      },
      handleClose() {
        this.$refs.formRef.resetFields()
        this.$emit('update:modelValue', false)
      },
    },
  }
</script>

// frontend/src/pages/mcp/components/AddConsumerAuth.tsx
import React, { useEffect, useState } from 'react';
import { Drawer, Form, Select, Button, message } from 'antd';
import { useTranslation } from 'react-i18next';
import { getConsumers } from '@/services/consumer';
import { addMcpConsumers } from '@/services/mcp';

interface AddConsumerAuthProps {
  visible: boolean;
  onClose: () => void;
  onSuccess: () => void;
  mcpName: string;
  strategyConfigId: string;
}

const AddConsumerAuth: React.FC<AddConsumerAuthProps> = ({
  visible,
  onClose,
  onSuccess,
  mcpName,
  strategyConfigId,
}) => {
  const { t } = useTranslation();
  const [form] = Form.useForm();
  const [consumerList, setConsumerList] = useState<Array<{ label: string; value: string }>>([]);
  const [loading, setLoading] = useState(false);

  const fetchConsumerList = async () => {
    try {
      const res = await getConsumers();
      setConsumerList(
        res.map((item: any) => ({
          label: item.name,
          value: item.name,
        })),
      );
    } catch (error) {
      message.error(t('mcp.detail.fetchConsumerListError'));
    }
  };

  useEffect(() => {
    if (visible) {
      fetchConsumerList();
      form.resetFields();
    }
  }, [visible]);

  const handleSubmit = async () => {
    try {
      const values = await form.validateFields();
      setLoading(true);
      await addMcpConsumers({
        mcpServerName: mcpName,
        consumers: [values.consumerId],
      });
      message.success(t('mcp.detail.authSuccess'));
      onSuccess();
      onClose();
    } catch (error) {
      message.error(t('mcp.detail.authError'));
    } finally {
      setLoading(false);
    }
  };

  const handleClose = () => {
    form.resetFields();
    onClose();
  };

  return (
    <Drawer
      title={t('mcp.detail.addConsumerAuth')}
      open={visible}
      onClose={handleClose}
      width={700}
      destroyOnClose
      footer={
        <div style={{ textAlign: 'right' }}>
          <Button onClick={handleClose} style={{ marginRight: 8 }}>
            {t('mcp.common.cancel')}
          </Button>
          <Button type="primary" onClick={handleSubmit} loading={loading}>
            {t('mcp.common.add')}
          </Button>
        </div>
      }
    >
      <Form form={form} layout="vertical" initialValues={{ consumerId: undefined }}>
        <Form.Item label={t('mcp.detail.authScope')}>MCP服务</Form.Item>
        <Form.Item
          name="consumerId"
          label={t('mcp.detail.consumer')}
          rules={[{ required: true, message: t('mcp.detail.selectConsumer') }]}
        >
          <Select
            placeholder={t('mcp.detail.selectConsumer')}
            options={consumerList}
            showSearch
            filterOption={(input, option) => (option?.label ?? '').toLowerCase().includes(input.toLowerCase())}
          />
        </Form.Item>
      </Form>
    </Drawer>
  );
};

export default AddConsumerAuth;
